### PR TITLE
Revert "Added id tags to wizard and group devices counter"

### PR DESCRIPTION
**Pull request by jerrytrieu**
Reverts advancedtelematic/ota-plus-server#1455

### CODE REVIEW

**Comment by jerrytrieu** [comment]
@volodymyrhudyma this patch causes `Error: Cannot find module "react-vis"`

**Comment by volodymyrhudyma** [comment]
Strange because I haven't used that module here. Should I do a rebase?

**Comment by volodymyrhudyma** [comment]
Locally I do not receive any errors. Does npm i runs without a problems on deploy?

**Comment by jerrytrieu** [comment]
This error occurred without stopping the build:
```
[09:51:52][Step 1/2] ERROR in ./src/partials/DependenciesModal.jsx
[09:51:52][Step 1/2] Module not found: Error: Can't resolve 'react-vis' in '/app/reactapp/src/partials'
```

**Comment by volodymyrhudyma** [comment]
Seems like the problem is when react-vis gets upgraded to the newest version 1.9.0. I will make the version of this package to be 1.8.0, so it won't get updated

**Comment by volodymyrhudyma** [comment]
Should I make changes in this branch and rebase it or create a new one?

**Comment by jerrytrieu** [comment]
You can create a new branch and PR. Let's close this one.

**Comment by volodymyrhudyma** [comment]
Done

**Pull request closed without merging**
