### PR TITLE
[PRO-5000] Re-add UI redesign

### PR DESCRIPTION
**Pull request by jerrytrieu**
Reverts advancedtelematic/ota-plus-server#1469

### CODE REVIEW

**Comment by jerrytrieu** [comment]
@volodymyrhudyma can you rebase this branch on latest master and resolve conflicts?

@jochenschneider can you merge PRs from @volodymyrhudyma this week?

**Comment by jerrytrieu** [comment]
@jochenschneider let's tag this commit version `v0.7.0`

**Comment by jochenschneider** [comment]
Sure. Do I need to put the release version number 0.7.0 somewhere else, as well?

**Comment by volodymyrhudyma** [comment]
@jochenschneider this branch is rebased

**Pull request merged**
