### PR TITLE
[OTA-3104 & OTA-3644] Handle account setup status for prov-keys + bump eslint-utils ver

### PR DESCRIPTION
**Pull request by piotrsmol**
Signed-off-by: Piotr Smol <piotrsmol.pvt@gmail.com>

### CODE REVIEW

**Comment by piotrsmol** [comment]
@zabbal This PR comes with a fix for critical severity issue - OTA-3644: Bump eslint-utils dependency version

**Comment by piotrsmol** [comment]
@zabbal No, it's an independent change. We fix most vulnerabilities (this one included) by simply running `npm audit fix` which scans and fixes all dependencies. Since it's a critical severity vulnerability, I decided to attach fix for it to this commit to get it faster on master.

**Comment by zabbal** [comment]
> We fix most vulnerabilities (this one included) by simply running `npm audit fix` which scans and fixes all dependencies. Since it's a critical severity vulnerability, I decided to attach fix for it to this commit to get it faster on master.

Cool, but it's much easier (and hence faster) to review when it's in separate commits with self-explanatory commit logs - even when it's bundled into same PR.

**Comment by piotrsmol** [comment]
@zabbal Okay, will keep that in mind next time :)

**Pull request merged**
