### PR TITLE
OTA-4542 : Allow user from any realm to access OTA Connect

### PR DESCRIPTION
**Pull request by kmanikandan-kmk**
References:
https://confluence.in.here.com/display/HEREAccount/Realm-aware+Application+Considerations
https://development-architecture.pages.gitlab.in.here.com/olp-apis/?urls.primaryName=aaa-oidc-v1#/OIDCFlow/Authorize

### CODE REVIEW

**Comment by kmanikandan-kmk** [comment]
I tested this pr locally. Having 'any-realm=true' and removing 'prompt' param enables seamless login with active HERE account (with or without realm). So, works for both XYZ Studio and Platform.here.com. However, this breaks logout flow as we are re-directing to login page during logout (which is a successful login session due to an active HERE account session). I am currently checking, how "logout" can clear HERE Account session so that user is prompted to login again.

**Comment by zabbal** [comment]
The linked page mention "OpenID Connect SDK" and ""HA Web SSO.js SDK" - which one are we actually using?

**Comment by kmanikandan-kmk** [comment]
> The linked page mention "OpenID Connect SDK" and ""HA Web SSO.js SDK" - which one are we actually using?

We are using "OpenID Connect API" which is most likely referred as "OpenID Connect SDK"

**Comment by houcros** [comment]
Thanks for this @kmanikandan-kmk!
I'm closing it for the moment as we're moving to Gitlab, and I might create a new PR as part of OTA-4636 if all goes well.

**Pull request closed without merging**
